### ISSUE TITLE
Output of the installation process

### ISSUE THREAD

**Issue by Crefeda** [HazyResearch/CaffeConTroll#51]
Hi,

I was following your instructions and I am unable to get the executable caffe-cct . Could you please send a snapshot of the installation.
I already have caffe installed and built.
Does the CaffeConTroll have to be inside the caffe root? Sorry, but I am a little confused.
I am trying to debug and it looks too crowded..
It looks like something like this...
![screenshot from 2016-03-02 17 14 44](https://cloud.githubusercontent.com/assets/10142038/13468418/64f07c1c-e09a-11e5-8058-50bf0f2f2510.png)

**Comment by shadjis** [comment]
Hi Crefeda,
Do you get a caffe-ct executable?

**Comment by Crefeda** [comment]
Hi Stefan,
No, I did not get it.

**Comment by shadjis** [comment]
Hi Crefeda,

Thanks. Can you please paste the full output of make? After the last line in your screenshot above what happens?

Thanks,
Stefan

**Comment by Crefeda** [comment]
Hi Stefan,

Here is the output
------------------------------------------------------------------------------------------------
crefeda@Faviola:~/Desktop/CaffeConTroll$ make clean && make -j all
rm -f caffe-ct
rm -f src/parser/*.pb.*
rm -f tests/test_main.o src/util.o src/timer.o src/DeepNetConfig.o src/sched/DeviceDriver_CPU.o tests/test_MaxPooling_bridge.o tests/test_parallelized_convolution.o tests/test_lrn_bridge.o tests/test_ReLU_bridge.o tests/test_parallelized_fc.o tests/test_parallelized_convolution_large_CPU.o tests/test_parallelized_convolution_large_CPU_batch.o tests/test_convolution.o tests/test_fc_bridge.o tests/test_kernel.o tests/test_connector.o tests/test_dropout_bridge.o tests/test_softmax_bridge.o tests/test_device_driver_cpu.o tests/test_cube.o tests/test_report.o tests/test_grouping.o tests/test_model_write.o tests/test_scanner.o tests/test_lenet_network.o
rm -f src/DeepNetConfig.o src/util.o src/timer.o src/main.o src/sched/DeviceDriver_CPU.o
rm -f test
rm -f tests/test_main.o src/util.o src/timer.o src/DeepNetConfig.o src/sched/DeviceDriver_CPU.o snapshot-parser/simple_parse.o tests/test_imagenet_snapshot.o
rm -f 
rm -f 
rm -f snapshot
rm -f src/*.d
rm -f tests/toprocess.bin tests/model.bin tests/model.bin.* tests/lenet_toprocess.bin tests/imgnet_toprocess.bin
cd src/parser/; protoc --cpp_out=. cnn.proto; cd -
/home/crefeda/Desktop/CaffeConTroll
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -c src/DeepNetConfig.cpp -o src/DeepNetConfig.o
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -c src/util.cpp -o src/util.o
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -c src/timer.cpp -o src/timer.o
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -c src/main.cpp -o src/main.o
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -c src/sched/DeviceDriver_CPU.cpp -o src/sched/DeviceDriver_CPU.o
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -c src/parser/cnn.pb.cc
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -MT src/DeepNetConfig.o -MM src/DeepNetConfig.cpp > src/DeepNetConfig.d
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -MT src/timer.o -MM src/timer.cpp > src/timer.d
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -MT src/util.o -MM src/util.cpp > src/util.d
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -MT src/sched/DeviceDriver_CPU.o -MM src/sched/DeviceDriver_CPU.cpp > src/sched/DeviceDriver_CPU.d
cc -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include   -MT src/main.o -MM src/main.cpp > src/main.d
cc src/DeepNetConfig.o src/util.o src/timer.o src/main.o src/sched/DeviceDriver_CPU.o cnn.pb.o  -o caffe-ct -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW   -llmdb  -lglog  -lopenblas -lrt -lboost_program_options -lboost_serialization -lpthread  -Ofast -D_FASTPOW   -I/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/include  -L/home/crefeda/Desktop/CaffeConTroll/OpenBLAS/lib  -llmdb  -lglog  -lopenblas -lrt -lboost_program_options -lboost_serialization -lpthread  -lprotobuf
/usr/bin/ld: src/main.o: undefined reference to symbol '__cxa_free_exception@@CXXABI_1.3'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
Could you please advisse

**Comment by shadjis** [comment]
Hi Crefeda,
Can you try editing Makefile and replacing `-lpthread` with `-lpthread -lstdc++` on line 28? If it fails can you again print the last few lines of the output?

**Comment by Crefeda** [comment]
Hi Stefan,

Here is the output
/usr/bin/ld: src/sched/DeviceDriver_CPU.o: undefined reference to symbol '__expf_finite@@GLIBC_2.15'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

**Comment by Crefeda** [comment]
Yes I was able to figure it out thanks. I have a executable now
