### ISSUE TITLE
Cannot compile on Linux

### ISSUE THREAD

**Issue by syadlowsky** [HazyResearch/CaffeConTroll#54]
> ```
g++  -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW     -MT src/timer.o -MM src/timer.cpp > src/timer.d
In file included from src/sched/DeviceDriver_CPU.h:2:0,
                 from src/sched/DeviceDriver_CPU.cpp:2:
src/sched/DeviceDriver.h:197:33: error: using typedef-name ‘CBLAS_ORDER’ after ‘enum’
   virtual void sgemm(const enum CBLAS_ORDER order, CBLAS_TRANSPOSE TA, CBLAS_TRANSPOSE TB,
                                 ^
In file included from src/sched/DeviceHeader.h:7:0,
                 from src/sched/DeviceDriver.h:8,
                 from src/sched/DeviceDriver_CPU.h:2,
                 from src/sched/DeviceDriver_CPU.cpp:2:
/usr/include/cblas.h:25:22: note: ‘CBLAS_ORDER’ has a previous declaration here
 typedef CBLAS_LAYOUT CBLAS_ORDER; /* this for backward compatibility with CBLAS_ORDER */
                      ^
In file included from src/sched/DeviceDriver_CPU.cpp:2:0:
src/sched/DeviceDriver_CPU.h:62:25: error: using typedef-name ‘CBLAS_ORDER’ after ‘enum’
   void sgemm(const enum CBLAS_ORDER order, CBLAS_TRANSPOSE TA, CBLAS_TRANSPOSE TB,
                         ^
In file included from src/sched/DeviceHeader.h:7:0,
                 from src/sched/DeviceDriver.h:8,
                 from src/sched/DeviceDriver_CPU.h:2,
                 from src/sched/DeviceDriver_CPU.cpp:2:
/usr/include/cblas.h:25:22: note: ‘CBLAS_ORDER’ has a previous declaration here
 typedef CBLAS_LAYOUT CBLAS_ORDER; /* this for backward compatibility with CBLAS_ORDER */
                      ^
src/sched/DeviceDriver_CPU.cpp: In member function ‘void CPUDriver::math_saxpby(int, float, float*, float, float*) const’:
src/sched/DeviceDriver_CPU.cpp:461:42: error: ‘cblas_saxpby’ was not declared in this scope
   cblas_saxpby(N, alpha, X, 1, beta, Y, 1);
                                          ^
src/sched/DeviceDriver_CPU.cpp: In member function ‘virtual void CPUDriver::set_num_threads(int)’:
src/sched/DeviceDriver_CPU.cpp:476:36: error: ‘openblas_set_num_threads’ was not declared in this scope
   openblas_set_num_threads(nThreads);
                                    ^
src/sched/DeviceDriver_CPU.cpp: At global scope:
src/sched/DeviceDriver_CPU.cpp:486:34: error: using typedef-name ‘CBLAS_ORDER’ after ‘enum’
 void CPUDriver::sgemm(const enum CBLAS_ORDER order, CBLAS_TRANSPOSE TA, CBLAS_TRANSPOSE TB,
                                  ^
In file included from src/sched/DeviceHeader.h:7:0,
                 from src/sched/DeviceDriver.h:8,
                 from src/sched/DeviceDriver_CPU.h:2,
                 from src/sched/DeviceDriver_CPU.cpp:2:
/usr/include/cblas.h:25:22: note: ‘CBLAS_ORDER’ has a previous declaration here
 typedef CBLAS_LAYOUT CBLAS_ORDER; /* this for backward compatibility with CBLAS_ORDER */
                      ^
src/sched/DeviceDriver_CPU.cpp: In member function ‘virtual void CPUDriver::sgemm(int, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float*, int, float*, int, float, float*, int)’:
src/sched/DeviceDriver_CPU.cpp:493:20: error: invalid conversion from ‘int’ to ‘CBLAS_LAYOUT’ [-fpermissive]
       beta, pC, LDC);
                    ^
In file included from src/sched/DeviceHeader.h:7:0,
                 from src/sched/DeviceDriver.h:8,
                 from src/sched/DeviceDriver_CPU.h:2,
                 from src/sched/DeviceDriver_CPU.cpp:2:
/usr/include/cblas.h:429:6: note:   initializing argument 1 of ‘void cblas_sgemm(CBLAS_LAYOUT, CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, const float*, int, const float*, int, float, float*, int)’
 void cblas_sgemm(CBLAS_LAYOUT layout, CBLAS_TRANSPOSE TransA,
      ^
Makefile:235: recipe for target 'src/sched/DeviceDriver_CPU.o' failed
make: *** [src/sched/DeviceDriver_CPU.o] Error 1
make: *** Waiting for unfinished jobs....
g++  -Wall -Wl,--no-as-needed -std=c++11 -D_USE_OPENBLAS -Ofast -D_FASTPOW     -MT src/util.o -MM src/util.cpp > src/util.d
In file included from src/LogicalCube.h:10:0,
                 from src/DeepNet.h:8,
                 from src/main.cpp:9:
src/sched/DeviceDriver.h:197:33: error: using typedef-name ‘CBLAS_ORDER’ after ‘enum’
   virtual void sgemm(const enum CBLAS_ORDER order, CBLAS_TRANSPOSE TA, CBLAS_TRANSPOSE TB,
                                 ^
In file included from src/sched/DeviceHeader.h:7:0,
                 from src/sched/DeviceDriver.h:8,
                 from src/LogicalCube.h:10,
                 from src/DeepNet.h:8,
                 from src/main.cpp:9:
/usr/include/cblas.h:25:22: note: ‘CBLAS_ORDER’ has a previous declaration here
 typedef CBLAS_LAYOUT CBLAS_ORDER; /* this for backward compatibility with CBLAS_ORDER */
                      ^
In file included from src/Connector_impl_Lowering_type1.hxx:19:0,
                 from src/Connector.h:124,
                 from src/Layer.h:13,
                 from src/DeepNet.h:9,
                 from src/main.cpp:9:
src/sched/DeviceDriver_CPU.h:62:25: error: using typedef-name ‘CBLAS_ORDER’ after ‘enum’
   void sgemm(const enum CBLAS_ORDER order, CBLAS_TRANSPOSE TA, CBLAS_TRANSPOSE TB,
                         ^
In file included from src/sched/DeviceHeader.h:7:0,
                 from src/sched/DeviceDriver.h:8,
                 from src/LogicalCube.h:10,
                 from src/DeepNet.h:8,
                 from src/main.cpp:9:
/usr/include/cblas.h:25:22: note: ‘CBLAS_ORDER’ has a previous declaration here
 typedef CBLAS_LAYOUT CBLAS_ORDER; /* this for backward compatibility with CBLAS_ORDER */
                      ^
Makefile:235: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 1
```

**Comment by syadlowsky** [comment]
Never mind--  my machine was still confusing cblas and openblas.

**Comment by jkim6047** [comment]
Hi Syadlowsky,
My machine is also confused...  Mine compiled fine for "make all" with openblas, but it is complaining about CBLAS_ORDER for "make test".  How did you fix the confusion?  Thanks.
JK
